services:
  - type: web
    name: kakashi-bot
    env: docker
    plan: starter
    region: oregon
    buildCommand: docker build -t app .
    startCommand: docker run --rm --env-file .env -p $PORT:8080 app
    healthCheckPath: /
    envVars: